# Generated by Django 4.2.2 on 2024-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='addresses',
            field=models.CharField(max_length=500),
        ),
    ]
